name: actions-usage

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  actions: read

jobs:
  actions-usage:
    name: daily-stats
    runs-on: actuated-arm64-1cpu-8gb
    steps:

# vmmeter start
    - uses: alexellis/arkade-get@master
      with:
        crane: latest
        print-summary: false
    - name: Install vmmeter
      run: |
        crane export --platform linux/arm64 ttl.sh/alexellis2/vmmeter:latest | sudo tar -xvf - -C /usr/local/bin
    - uses: self-actuated/vmmeter-action@master
# vmmeter end

    - uses: alexellis/arkade-get@master
      with:
        actions-usage: latest
        print-summary: false
    - name: Generate actions-usage report
      run: |
       echo "### Actions Usage report by [actuated.dev](https://actuated.dev)" >> SUMMARY
       echo "\`\`\`" >> SUMMARY
       actions-usage \
        -org $GITHUB_REPOSITORY_OWNER \
        -days 1 \
        -by-repo \
        -punch-card \
        -token ${{ secrets.GITHUB_TOKEN }}  2> /dev/null  >> SUMMARY
       echo "\`\`\`" >> SUMMARY
       cat SUMMARY >> $GITHUB_STEP_SUMMARY
