name: actions-usage

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  actions: read

jobs:
  actions-usage:
    name: daily-stats
    runs-on: actuated-any-1cpu-2gb
    steps:
    - uses: alexellis/arkade-get@master
      with:
        actions-usage: latest
    - name: Generate actions-usage report
      run: |
       echo "### Actions Usage report by [actuated.dev](https://actuated.dev)" >> SUMMARY
       echo "\`\`\`" >> SUMMARY
       actions-usage \
        -org $GITHUB_REPOSITORY_OWNER \
        -days 1 \
        -by-repo \
        -punch-card \
        -token ${{ secrets.GITHUB_TOKEN }}  2> /dev/null  >> SUMMARY
       echo "\`\`\`" >> SUMMARY
       cat SUMMARY >> $GITHUB_STEP_SUMMARY
