name: get-stats

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  get-stats:
    name: connect
    runs-on: actuated
    steps:
    - uses: alexellis/arkade-get@master
      with:
        actions-usage: latest
    - run: |
       actions-usage --org $GITHUB_REPOSITORY_OWNER --days 1 --by-repo -punch-card --token ${GITHUB_TOKEN}
